//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VsWebServiceTestClient.WsReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tapws.vicko.rs/", ConfigurationName="WsReference.TapWebService")]
    public interface TapWebService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tapws.vicko.rs/TapWebService/sayHelloRequest", ReplyAction="http://tapws.vicko.rs/TapWebService/sayHelloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        VsWebServiceTestClient.WsReference.sayHelloResponse sayHello(VsWebServiceTestClient.WsReference.sayHelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tapws.vicko.rs/TapWebService/sayHelloRequest", ReplyAction="http://tapws.vicko.rs/TapWebService/sayHelloResponse")]
        System.Threading.Tasks.Task<VsWebServiceTestClient.WsReference.sayHelloResponse> sayHelloAsync(VsWebServiceTestClient.WsReference.sayHelloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tapws.vicko.rs/TapWebService/getUserbyNameRequest", ReplyAction="http://tapws.vicko.rs/TapWebService/getUserbyNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        VsWebServiceTestClient.WsReference.getUserbyNameResponse getUserbyName(VsWebServiceTestClient.WsReference.getUserbyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tapws.vicko.rs/TapWebService/getUserbyNameRequest", ReplyAction="http://tapws.vicko.rs/TapWebService/getUserbyNameResponse")]
        System.Threading.Tasks.Task<VsWebServiceTestClient.WsReference.getUserbyNameResponse> getUserbyNameAsync(VsWebServiceTestClient.WsReference.getUserbyNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHello", WrapperNamespace="http://tapws.vicko.rs/", IsWrapped=true)]
    public partial class sayHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tapws.vicko.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public sayHelloRequest() {
        }
        
        public sayHelloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sayHelloResponse", WrapperNamespace="http://tapws.vicko.rs/", IsWrapped=true)]
    public partial class sayHelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tapws.vicko.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sayHelloResponse() {
        }
        
        public sayHelloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tapws.vicko.rs/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fullNameField;
        
        private int idField;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("fullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserbyName", WrapperNamespace="http://tapws.vicko.rs/", IsWrapped=true)]
    public partial class getUserbyNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tapws.vicko.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public getUserbyNameRequest() {
        }
        
        public getUserbyNameRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserbyNameResponse", WrapperNamespace="http://tapws.vicko.rs/", IsWrapped=true)]
    public partial class getUserbyNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tapws.vicko.rs/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public VsWebServiceTestClient.WsReference.user @return;
        
        public getUserbyNameResponse() {
        }
        
        public getUserbyNameResponse(VsWebServiceTestClient.WsReference.user @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TapWebServiceChannel : VsWebServiceTestClient.WsReference.TapWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TapWebServiceClient : System.ServiceModel.ClientBase<VsWebServiceTestClient.WsReference.TapWebService>, VsWebServiceTestClient.WsReference.TapWebService {
        
        public TapWebServiceClient() {
        }
        
        public TapWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TapWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TapWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TapWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VsWebServiceTestClient.WsReference.sayHelloResponse VsWebServiceTestClient.WsReference.TapWebService.sayHello(VsWebServiceTestClient.WsReference.sayHelloRequest request) {
            return base.Channel.sayHello(request);
        }
        
        public string sayHello(string name) {
            VsWebServiceTestClient.WsReference.sayHelloRequest inValue = new VsWebServiceTestClient.WsReference.sayHelloRequest();
            inValue.name = name;
            VsWebServiceTestClient.WsReference.sayHelloResponse retVal = ((VsWebServiceTestClient.WsReference.TapWebService)(this)).sayHello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VsWebServiceTestClient.WsReference.sayHelloResponse> VsWebServiceTestClient.WsReference.TapWebService.sayHelloAsync(VsWebServiceTestClient.WsReference.sayHelloRequest request) {
            return base.Channel.sayHelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsWebServiceTestClient.WsReference.sayHelloResponse> sayHelloAsync(string name) {
            VsWebServiceTestClient.WsReference.sayHelloRequest inValue = new VsWebServiceTestClient.WsReference.sayHelloRequest();
            inValue.name = name;
            return ((VsWebServiceTestClient.WsReference.TapWebService)(this)).sayHelloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VsWebServiceTestClient.WsReference.getUserbyNameResponse VsWebServiceTestClient.WsReference.TapWebService.getUserbyName(VsWebServiceTestClient.WsReference.getUserbyNameRequest request) {
            return base.Channel.getUserbyName(request);
        }
        
        public VsWebServiceTestClient.WsReference.user getUserbyName(string name) {
            VsWebServiceTestClient.WsReference.getUserbyNameRequest inValue = new VsWebServiceTestClient.WsReference.getUserbyNameRequest();
            inValue.name = name;
            VsWebServiceTestClient.WsReference.getUserbyNameResponse retVal = ((VsWebServiceTestClient.WsReference.TapWebService)(this)).getUserbyName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VsWebServiceTestClient.WsReference.getUserbyNameResponse> VsWebServiceTestClient.WsReference.TapWebService.getUserbyNameAsync(VsWebServiceTestClient.WsReference.getUserbyNameRequest request) {
            return base.Channel.getUserbyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<VsWebServiceTestClient.WsReference.getUserbyNameResponse> getUserbyNameAsync(string name) {
            VsWebServiceTestClient.WsReference.getUserbyNameRequest inValue = new VsWebServiceTestClient.WsReference.getUserbyNameRequest();
            inValue.name = name;
            return ((VsWebServiceTestClient.WsReference.TapWebService)(this)).getUserbyNameAsync(inValue);
        }
    }
}
